import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { LoginPage } from "@/pages/Form";
import Title from "@/components/Title/Title";


export default function Home() {
  return (
    <>
      <Head>
        <title>LoginFlow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className={styles.main}>
        <div className={styles.leftSection}>
          <Title text="Página de Login" />
          <p className={styles.subtitle}>Faça login para acessar sua conta</p>
        </div>
        <div className={styles.rightSection}>
          <LoginPage />
        </div>
      </main>

    </>
  );
}
